### PR TITLE
[RSDK-8586]   Patch things post-migration

### PR DESCRIPTION
**Pull request by hexbabe**
[RSDK-8586](https://viam.atlassian.net/browse/RSDK-8586)

[RSDK-8586]: https://viam.atlassian.net/browse/RSDK-8586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by hexbabe** [comment]
@seanavery noticing that all the deploy stuff is manual and there is no CI. This is all we have to do right?

**Comment by hexbabe** [comment]
> @seanavery noticing that all the deploy stuff is manual and there is no CI. This is all we have to do right?

Bumping for a confirmation just in case

**Comment by hexbabe** [comment]
@seanavery

**Review by seanavery — APPROVED** [review]
LGTM. 

No CI integration in this repo yet so small diff to meta.json seems sufficient.

**Pull request merged**
